apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: poc
  namespace: {{ .Values.argocdNamespace }}
spec:
  description: KrakenD GitOps proof of concept
  sourceRepos:
    - {{ .Values.repoURL | quote }}
    - https://argoproj.github.io/argo-helm
    - https://codecentric.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.argocdNamespace }}
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.krakend.namespace }}
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.demoApiNamespace }}
    - server: https://kubernetes.default.svc
      namespace: {{ .Values.keycloak.namespace }}
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
