apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: krakend-poc
resources:
  - deployment.yaml
  - service.yaml
